#version: '3'
#services:
#    web:
#        build: .
#        ports:
#            - "5000:5000"
#        volumes:
#            - .:/code
#        depends_on:
#            - redis
#    redis:
#        image: redis

web:
    build: .
    command: python -u MainScores.py
    ports:
        - "5000:5000"
    volumes:
        - .:/code
redis:
    image: redis